source 'https://rubygems.org'

gem 'rails', '~> 7.0.4'
gem 'pg', '~> 1.4.6'
gem 'puma', '~> 6.2.2'
gem 'devise', '~> 4.9.2'
gem 'faraday', '~> 2.7.4'
gem 'sidekiq', '~> 7.0.9'
gem 'redis', '~> 5.0.6'

group :development, :test do
  gem 'rspec-rails', '~> 6.0.1'
  gem 'factory_bot_rails', '~> 6.2.0'
  gem 'rubocop', '~> 1.50.2'
  gem 'debug', '~> 1.7.2'
end

group :test do
  gem 'capybara', '~> 3.39.0'
  gem 'webmock', '~> 3.18.1'
end
