source 'https://rubygems.org'

gem 'rails', '5.2.0'
gem 'nokogiri', '1.10.8'
gem 'loofah', '2.2.3'
gem 'pg', '~> 1.1.0'
gem 'puma', '~> 3.12.0'
gem 'devise', '~> 4.7.0'
gem 'faraday', '~> 1.0.0'
gem 'sidekiq', '~> 5.2.0'
gem 'redis', '~> 4.1.0'

group :development, :test do
  gem 'rspec-rails', '~> 3.8.0'
  gem 'factory_bot_rails', '~> 5.0.0'
  gem 'rubocop', '~> 0.74.0'
end

group :test do
  gem 'capybara', '~> 3.28.0'
  gem 'webmock', '~> 3.7.0'
end
