# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'CocoaPodsExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CocoaPodsExample
  pod 'Alamofire', '~> 5.8'
  pod 'SDWebImage', '~> 5.18'
  pod 'SnapKit', '~> 5.6'
  pod 'SwiftyJSON', '~> 5.0'
  pod 'RxSwift', '~> 6.6'
  pod 'RxCocoa', '~> 6.6'

  target 'CocoaPodsExampleTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Quick', '~> 7.3'
    pod 'Nimble', '~> 12.3'
  end

  target 'CocoaPodsExampleUITests' do
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
